# Makefile.mingw
#
# Description: Top Makefile for musictracker plugin.
#

.PHONY: all installer clean

MINGW_MAKEFILE=Makefile.mingw

all: 
	$(MAKE) -C src -f $(MINGW_MAKEFILE)
	$(MAKE) -C po -f $(MINGW_MAKEFILE)

installer: all 
	$(MAKE) -C src -f $(MINGW_MAKEFILE) installer

clean:
	$(MAKE) -C src -f $(MINGW_MAKEFILE) clean
	$(MAKE) -C po -f $(MINGW_MAKEFILE) clean
